export const profile = {
    name: 'Christopher McDonald',
    title: 'Software Engineer',
    about: 'Motivated and innovative software engineer with a strong background in developing full-stack technology solutions. 4+ years experience with React as both Class and Functional components, fluency in TypeScript/JavaScript, Kotlin/Java, Python and Swift. Passionate about delivering value, regardless of if that is delivering new features or paying back tech debt. A former Physics and Mathematics secondary school teacher that is multilingual, an emerging leader, has a proven ability to work effectively in a team environment, and has exceptional written and oral communication skills.',
    quote: `"You don't know what you don't know." - unknown`,
    skills: 'AWS,Typescript/JavaScript, React, React Native, Expo, Kotlin, Java, Python, Swift, SwiftUI, Git, CLI, Auth0/AzureAD/SSO,  MongoDB, MySQL/Postgres, Insomnia/Postman, RabbitMQ, Kafka, Elastic/Kibana, Docker, Google Play store, Apple store, VSC, IntelliJ, Xcode, Jira.',
    competencies: [
        'Planning and building components for React Storybook UI library from Figma designs.',
        'Planning and building features for React NextJS Web Application.',
        'Developing endpoints and features for backend (MACH architecture).',
        'Building interface for, and integrating application with, GraphQL headless CMS.',
        'Representing team and providing developer input for prioritisation, estimation and planning sessions.',
        'Contributing to AGILE team ceremonies - including backlog refinement, retro, sprint review.',
        'Showcasing and presenting new features in client meetings.',
        'Working tightly coupled with Design, Data and QA teams.',
        'Facilitating and participating in regular PRs and PR swarms.',
        'Planning and facilitating learning sessions for fellow developers.',
        'Participating in regular architecture solution discussions as WebX subject matter expert.',
    ],
    furtherExperience: [
        'Planned and delivered micro service for monitoring the automated Withdrawals process.',
        'Planned and delivered end-to-end specialised process for rectifying client accounts - integrating with existing architecture.',
        'Developed and maintained features for both front end (React UI) and back end (Microservice/REST).',
        'Contribute towards meetings with stakeholders. ',
        'Participate in and deliver team meetings assisting in the adoption of new technologies.',
        'Review client requests and discuss possible solutions that is supported by data.',
        'Created and updated domain knowledge and business logic within documentation.',
        'Monitor, investigate, evaluate active and new micro services.',
        'Follow CI/CD best practices with team.',
        'Develop bug fixes using a suite of Full-stack Technologies.',
    ],
    bio: "I started my programming journey while studying my Masters of Education in early 2018. At the time I was researching advanced pedagogical methods and one area of study included big data and machine learning. These concepts really appealed to me so when I completed my Masters degree I started learning how to code. Subscribed to Codecademy's service, I initially learnt Python until late 2018 when my understanding culminated in projects that developed skills such as scraping websites, visualising data, and using machine learning algorithms. I then became interested in learning Javascript as it is popular in both front-end and back-end applications. Along the javascript journey I developed HTML, CSS, CLI skills as well as best practices in version control, TDD, authentication, authorisation and accessibility.\nCertificates for courses I completed while learning include Full-Stack Developer, Front-End Developer, Back-End Developer, Authentication and Authorisation and Java for Programmers to name a few, and can be found on my LinkedIn page.\nSince late 2020 I have spent most of my free time working on various personal projects developing fluency using high end technologies such as React, Node, Express, React Native, Expo, MySQL/Postgres, MongoDB, Amazon Web Services (AWS) and Swift to name a few.\nPrior to my change in career, I was a Physics and Mathematics secondary school teacher for 6 years. A few last noteworthy points about me: I am new father, I am an avid snowboarder, I have lived in Canada and Germany, I speak German and I ride motorbikes.",
    contactPageMessage:
        'To contact me please send a message on LinkedIn or comment on GitHub',
}
